name: test
on: [pull_request]

jobs:
  dev-tools:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Test Devs tools, compil and lint
      uses: actions/setup-node@v2
    - run: npm install  
    - run: npm build  
    - run: npm run lint  
    - run: npm run commit:fake  
  unit-tests:
   runs-on: ubuntu-latest
   strategy:
    matrix:
      node-version: [10.x, 12.x, 14.x]  
      puppeteer-version: [1, 2, 3, 4, 5]
   steps:
    - uses: actions/checkout@v2
    - name: npm test node ${{matrix.node-version}} puppeteer ${{matrix.puppeteer-version}}
      uses: actions/setup-node@v2      
      with:
        node-version: ${{ matrix.node-version }}      
    - run: npm install  
    - run: npm install @types/puppeteer@${{matrix.puppeteer-version}}
      if: ${{ matrix.puppeteer-version < 4 }}
    - run: npm install @types/puppeteer@3
      if: ${{ matrix.puppeteer-version >= 4 }}      
    - run: npm install puppeteer@${{matrix.puppeteer-version}}
    - run: npm test
